spring:
  application:
    name: vuitton
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/home/moriaty/work/workspace/IDEA/vuitton-tool/vuitton.db
  web:
    resources:
      static-locations: classpath:/static/
logging:
  level:
    com.moriaty.vuitton.dao.mapper: INFO
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
file-server:
  url: http://%s:8100
  novel:
    location: /data/novel
    url-prefix: /novel
    default-novel-img: ${file-server.novel.url-prefix}/default_img.jpg
    module-local-img: ${file-server.novel.url-prefix}/module_local_novel_img.jpg
    module-network-img: ${file-server.novel.url-prefix}/module_network_novel_img.jpeg
  video:
    location: /data/video
    url-prefix: /video
    module-video-img: ${file-server.video.url-prefix}/module_video_img.webp