spring:
  application:
    name: vuitton
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/home/moriaty/work/workspace/IDEA/vuitton/vuitton.db
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
logging:
  level:
    com.moriaty.vuitton.dao.mapper: DEBUG
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
file-server:
  url: http://%s:8081
  novel:
    location: /data/novel/
  video:
    base-path: /data/video
    base-prefix: /video/